FROM python:3.10-slim

WORKDIR /app


RUN apt update -y \
    && apt install -y build-essential libpq-dev \
    && pip install poetry
COPY pyproject.toml poetry.lock ./
RUN poetry config virtualenvs.create false \
    && poetry install

COPY src ./src
COPY .env ./

CMD ["uvicorn", "src.app:app", "--host", "0.0.0.0", "--port", "8000", "--workers", "4"]
