version: "3.9"

services:
  backend:
    build: .
    container_name: backend
    volumes:
      - .:/app/
    env_file:
      - .env
    ports:
      - "8000:8000"
    restart: always
    depends_on:
      - postgres
      - redis
    command: uvicorn src.app:app --host 0.0.0.0 --port 8000 --reload

  postgres:
    image: postgres:14-alpine
    container_name: postgres
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - .env

  redis:
    image: redis:7-alpine
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

volumes:
  pgdata:
  redisdata:
