"""volunteer service, profile and ticket

Revision ID: 1f6caca61631
Revises: 37e5086635ee
Create Date: 2022-10-05 16:58:44.575720

"""
import sqlalchemy as sa
from geoalchemy2 import Geography
from sqlalchemy.dialects import postgresql

from alembic import op


# revision identifiers, used by Alembic.
revision = "1f6caca61631"
down_revision = "37e5086635ee"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "volunteerprofilemodels",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column(
            "location", Geography(geometry_type="POINT", from_text="ST_GeogFromText", name="geography"), nullable=False
        ),
        sa.Column("area_size", sa.Integer(), nullable=False),
        sa.Column("city", sa.String(length=100), nullable=False),
        sa.Column("working_from", sa.Time(), nullable=False),
        sa.Column("working_to", sa.Time(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_volunteerprofilemodels_id"), "volunteerprofilemodels", ["id"], unique=False)
    op.create_table(
        "volunteerservicemodels",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_volunteerservicemodels_id"), "volunteerservicemodels", ["id"], unique=False)
    op.create_table(
        "ticketmodels",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column(
            "location", Geography(geometry_type="POINT", from_text="ST_GeogFromText", name="geography"), nullable=False
        ),
        sa.Column("city", sa.String(length=100), nullable=False),
        sa.Column("description", sa.String(length=1000), nullable=False),
        sa.Column("valid_until", sa.DateTime(), nullable=False),
        sa.Column("user_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["usermodels.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_ticketmodels_id"), "ticketmodels", ["id"], unique=False)
    op.create_table(
        "volunteer_profile_to_service",
        sa.Column("volunteer_profile_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("volunteer_service_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["volunteer_profile_id"],
            ["volunteerprofilemodels.id"],
        ),
        sa.ForeignKeyConstraint(
            ["volunteer_service_id"],
            ["volunteerservicemodels.id"],
        ),
    )
    op.create_table(
        "ticket_to_volunteer_service",
        sa.Column("ticket_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("volunteer_service_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["ticket_id"],
            ["ticketmodels.id"],
        ),
        sa.ForeignKeyConstraint(
            ["volunteer_service_id"],
            ["volunteerservicemodels.id"],
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("ticket_to_volunteer_service")
    op.drop_table("volunteer_profile_to_service")
    op.drop_index(op.f("ix_ticketmodels_id"), table_name="ticketmodels")
    op.drop_index("idx_ticketmodels_location", table_name="ticketmodels", postgresql_using="gist")
    op.drop_table("ticketmodels")
    op.drop_index(op.f("ix_volunteerservicemodels_id"), table_name="volunteerservicemodels")
    op.drop_table("volunteerservicemodels")
    op.drop_index(op.f("ix_volunteerprofilemodels_id"), table_name="volunteerprofilemodels")
    op.drop_index("idx_volunteerprofilemodels_location", table_name="volunteerprofilemodels", postgresql_using="gist")
    op.drop_table("volunteerprofilemodels")
    # ### end Alembic commands ###
