"""userrole

Revision ID: 37e5086635ee
Revises: bab96c6e65c9
Create Date: 2022-10-03 23:41:29.578153

"""
import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision = "37e5086635ee"
down_revision = "bab96c6e65c9"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("usermodels", sa.Column("role", sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("usermodels", "role")
    # ### end Alembic commands ###
