"""add chat models

Revision ID: 3f67241b95b1
Revises: d44536341b56
Create Date: 2022-10-08 17:46:20.049591

"""
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op


# revision identifiers, used by Alembic.
revision = "3f67241b95b1"
down_revision = "d44536341b56"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "chatrequestmodels",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("requester_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("requested_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("has_unread_messages", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["requested_id"],
            ["usermodels.id"],
        ),
        sa.ForeignKeyConstraint(
            ["requester_id"],
            ["usermodels.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_chatrequestmodels_id"), "chatrequestmodels", ["id"], unique=False)
    op.create_table(
        "chatmessagemodels",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("chat_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("sender_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("message", sa.String(length=512), nullable=False),
        sa.ForeignKeyConstraint(
            ["chat_id"],
            ["chatrequestmodels.id"],
        ),
        sa.ForeignKeyConstraint(
            ["sender_id"],
            ["usermodels.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_chatmessagemodels_id"), "chatmessagemodels", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_chatmessagemodels_id"), table_name="chatmessagemodels")
    op.drop_table("chatmessagemodels")
    op.drop_index(op.f("ix_chatrequestmodels_id"), table_name="chatrequestmodels")
    op.drop_table("chatrequestmodels")
    # ### end Alembic commands ###
