"""volunteer review model

Revision ID: 7e7e96fd3366
Revises: daefb8b27755
Create Date: 2022-10-09 01:34:44.956322

"""
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op


# revision identifiers, used by Alembic.
revision = "7e7e96fd3366"
down_revision = "daefb8b27755"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "volunteerreviewmodels",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("reviewer_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("volunteer_profile_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("rate", sa.Integer(), nullable=False),
        sa.Column("text", sa.String(length=100), nullable=False),
        sa.ForeignKeyConstraint(
            ["reviewer_id"],
            ["usermodels.id"],
        ),
        sa.ForeignKeyConstraint(
            ["volunteer_profile_id"],
            ["volunteerprofilemodels.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_volunteerreviewmodels_id"), "volunteerreviewmodels", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_volunteerreviewmodels_id"), table_name="volunteerreviewmodels")
    op.drop_table("volunteerreviewmodels")
    # ### end Alembic commands ###
