"""volunteer profile user foreign key

Revision ID: ac7e8b045176
Revises: d3eb34ed6a4e
Create Date: 2022-10-07 07:13:31.449711

"""
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op


# revision identifiers, used by Alembic.
revision = "ac7e8b045176"
down_revision = "d3eb34ed6a4e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("volunteerprofilemodels", sa.Column("user_id", postgresql.UUID(as_uuid=True), nullable=False))
    op.create_foreign_key(None, "volunteerprofilemodels", "usermodels", ["user_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "volunteerprofilemodels", type_="foreignkey")
    op.drop_column("volunteerprofilemodels", "user_id")
    # ### end Alembic commands ###
