"""ticket_title

Revision ID: d1ed45a4c00a
Revises: e03624f77a80
Create Date: 2022-10-08 22:00:58.046169

"""
import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision = "d1ed45a4c00a"
down_revision = "e03624f77a80"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("ticketmodels", sa.Column("title", sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("ticketmodels", "title")
    # ### end Alembic commands ###
