"""Add unique to user foreign key

Revision ID: d44536341b56
Revises: ac7e8b045176
Create Date: 2022-10-07 07:36:27.194759

"""
import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision = "d44536341b56"
down_revision = "ac7e8b045176"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "volunteerprofilemodels", ["user_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "volunteerprofilemodels", type_="unique")
    # ### end Alembic commands ###
