"""volunteer review

Revision ID: daefb8b27755
Revises: e2d147175ed5
Create Date: 2022-10-08 23:46:48.958581

"""
import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision = "daefb8b27755"
down_revision = "e2d147175ed5"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
