"""add otp fields

Revision ID: e03624f77a80
Revises: 3f67241b95b1
Create Date: 2022-10-08 19:01:05.855086

"""
import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision = "e03624f77a80"
down_revision = "3f67241b95b1"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("usermodels", sa.Column("otp_code", sa.Integer(), nullable=True))
    op.add_column("usermodels", sa.Column("otp_code_issued_at", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("usermodels", "otp_code_issued_at")
    op.drop_column("usermodels", "otp_code")
    # ### end Alembic commands ###
