"""ticket status

Revision ID: e2d147175ed5
Revises: d1ed45a4c00a
Create Date: 2022-10-08 23:36:07.015840

"""
import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision = "e2d147175ed5"
down_revision = "d1ed45a4c00a"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("ticketmodels", sa.Column("status", sa.String(length=30), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("ticketmodels", "status")
    # ### end Alembic commands ###
