"""

Revision ID: e567f4b93108
Revises: e9c1fcbff4ac
Create Date: 2022-10-03 20:54:19.978588

"""
import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision = "e567f4b93108"
down_revision = "e9c1fcbff4ac"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("usermodels", sa.Column("created_at", sa.DateTime(), nullable=True))
    op.add_column("usermodels", sa.Column("updated_at", sa.DateTime(), nullable=True))
    op.add_column("usermodels", sa.Column("first_name", sa.String(length=100), nullable=False))
    op.add_column("usermodels", sa.Column("last_name", sa.String(length=100), nullable=False))
    op.add_column("usermodels", sa.Column("phone_number", sa.String(length=50), nullable=True))
    op.add_column("usermodels", sa.Column("image", sa.String(), nullable=True))
    op.add_column("usermodels", sa.Column("is_verified", sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("usermodels", "is_verified")
    op.drop_column("usermodels", "image")
    op.drop_column("usermodels", "phone_number")
    op.drop_column("usermodels", "last_name")
    op.drop_column("usermodels", "first_name")
    op.drop_column("usermodels", "updated_at")
    op.drop_column("usermodels", "created_at")
    # ### end Alembic commands ###
